name: endpoint_core
description: "A flexible and powerful Dart package for streamlined API integration in Flutter apps, featuring easy endpoint definition, caching, and customizable authentication."
version: 1.0.2
repository: "https://github.com/UcGeorge/Endpoint-Core"

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito:
  test:
  build_runner:

flutter:
  # ...
